### ISSUE TITLE
stuck in update loop

### ISSUE THREAD

**Issue by core-code** [DEmpire412/macbot-releases#1]
the appcast promises version 49 but downloads version 48:

      ```      <sparkle:version>49</sparkle:version>```
=>

 https://github.com/DEmpire412/macbot-releases/releases/download/prod/MacBot.dmg

so, even after updating you'll be prompted to update again:
<img width="732" alt="Screenshot 2024-02-06 at 18 22 39" src="https://github.com/DEmpire412/macbot-releases/assets/1261954/0c2c195b-69cf-4d96-951f-02e8a1e6ed2c">

**Comment by DEmpire412** [comment]
Fixed it

**Comment by core-code** [comment]
thanks!
